In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("fetal_health.csv")
X = df.drop('fetal_health', axis=1)
y = df['fetal_health']

#Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
#Check if there is any missing values
missing_values = df.isnull().sum()
print(missing_values.sum())

0


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#3 models
models = {
    'Random Forest': RandomForestClassifier(random_state=42),
    'SVM': SVC(random_state=42),
    'KNN': KNeighborsClassifier()
}

In [ ]:
#train and evaluate each model
for name, model in models.items():
    #Train Model
    model.fit(X_train, y_train)

    #Predict the test set
    y_pred = model.predict(X_test)

    #Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    #classification report
    class_report = classification_report(y_test, y_pred)

    #confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)

    # Print the results
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(class_report)
    print("Confusion Matrix:")
    print(conf_matrix)
    print("\n" + "="*60 + "\n")

Model: Random Forest
Accuracy: 0.9484
Classification Report:
              precision    recall  f1-score   support

         1.0       0.96      0.99      0.97       314
         2.0       0.92      0.79      0.85        75
         3.0       0.90      0.95      0.92        37

    accuracy                           0.95       426
   macro avg       0.93      0.91      0.91       426
weighted avg       0.95      0.95      0.95       426

Confusion Matrix:
[[310   4   0]
 [ 12  59   4]
 [  1   1  35]]


Model: SVM
Accuracy: 0.8427
Classification Report:
              precision    recall  f1-score   support

         1.0       0.86      0.98      0.92       314
         2.0       0.65      0.43      0.52        75
         3.0       0.91      0.54      0.68        37

    accuracy                           0.84       426
   macro avg       0.81      0.65      0.70       426
weighted avg       0.83      0.84      0.83       426

Confusion Matrix:
[[307   7   0]
 [ 41  32   2]
 [  7  10  2

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

# Additional models
moreModels = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=10000),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'Neural Network': MLPClassifier(random_state=42, max_iter=10000),
    'AdaBoost': AdaBoostClassifier(random_state=42),
    'Extra Trees': ExtraTreesClassifier(random_state=42)
}

models.update(moreModels)

for name, model in models.items():
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    class_report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    print(f"Model: {name}")
    print(f"Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(class_report)
    print("Confusion Matrix:")
    print(conf_matrix)
    print("\n" + "="*60 + "\n")

Model: Random Forest
Accuracy: 0.9484
Classification Report:
              precision    recall  f1-score   support

         1.0       0.96      0.99      0.97       314
         2.0       0.92      0.79      0.85        75
         3.0       0.90      0.95      0.92        37

    accuracy                           0.95       426
   macro avg       0.93      0.91      0.91       426
weighted avg       0.95      0.95      0.95       426

Confusion Matrix:
[[310   4   0]
 [ 12  59   4]
 [  1   1  35]]


Model: SVM
Accuracy: 0.8427
Classification Report:
              precision    recall  f1-score   support

         1.0       0.86      0.98      0.92       314
         2.0       0.65      0.43      0.52        75
         3.0       0.91      0.54      0.68        37

    accuracy                           0.84       426
   macro avg       0.81      0.65      0.70       426
weighted avg       0.83      0.84      0.83       426

Confusion Matrix:
[[307   7   0]
 [ 41  32   2]
 [  7  10  2

In [ ]:
#best models found were Gradient Boosting and also Random Forest
# Model: Random Forest
# Accuracy: 0.9484
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.96      0.99      0.97       314
#          2.0       0.92      0.79      0.85        75
#          3.0       0.90      0.95      0.92        37

#     accuracy                           0.95       426
#    macro avg       0.93      0.91      0.91       426
# weighted avg       0.95      0.95      0.95       426

# Confusion Matrix:
# [[310   4   0]
#  [ 12  59   4]
#  [  1   1  35]]

# ============================================================

# Model: SVM
# Accuracy: 0.8427
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.86      0.98      0.92       314
#          2.0       0.65      0.43      0.52        75
#          3.0       0.91      0.54      0.68        37

#     accuracy                           0.84       426
#    macro avg       0.81      0.65      0.70       426
# weighted avg       0.83      0.84      0.83       426

# Confusion Matrix:
# [[307   7   0]
#  [ 41  32   2]
#  [  7  10  20]]

# ============================================================

# Model: KNN
# Accuracy: 0.9085
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.90      0.99      0.94       314
#          2.0       0.92      0.64      0.76        75
#          3.0       0.94      0.78      0.85        37

#     accuracy                           0.91       426
#    macro avg       0.92      0.80      0.85       426
# weighted avg       0.91      0.91      0.90       426

# Confusion Matrix:
# [[310   4   0]
#  [ 25  48   2]
#  [  8   0  29]]

# ============================================================

# Model: Logistic Regression
# Accuracy: 0.8920
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.93      0.97      0.95       314
#          2.0       0.78      0.60      0.68        75
#          3.0       0.78      0.84      0.81        37

#     accuracy                           0.89       426
#    macro avg       0.83      0.80      0.81       426
# weighted avg       0.89      0.89      0.89       426

# Confusion Matrix:
# [[304  10   0]
#  [ 21  45   9]
#  [  3   3  31]]

# ============================================================

# Model: Decision Tree
# Accuracy: 0.9155
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.95      0.95      0.95       314
#          2.0       0.77      0.76      0.77        75
#          3.0       0.95      0.95      0.95        37

#     accuracy                           0.92       426
#    macro avg       0.89      0.88      0.89       426
# weighted avg       0.92      0.92      0.92       426

# Confusion Matrix:
# [[298  16   0]
#  [ 16  57   2]
#  [  1   1  35]]

# ============================================================

# Model: Gradient Boosting
# Accuracy: 0.9554
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.97      0.98      0.98       314
#          2.0       0.90      0.85      0.88        75
#          3.0       0.89      0.92      0.91        37

#     accuracy                           0.96       426
#    macro avg       0.92      0.92      0.92       426
# weighted avg       0.95      0.96      0.96       426

# Confusion Matrix:
# [[309   5   0]
#  [  7  64   4]
#  [  1   2  34]]

# ============================================================

# Model: Naive Bayes
# Accuracy: 0.8122
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.96      0.83      0.89       314
#          2.0       0.53      0.81      0.64        75
#          3.0       0.62      0.62      0.62        37

#     accuracy                           0.81       426
#    macro avg       0.70      0.76      0.72       426
# weighted avg       0.85      0.81      0.82       426

# Confusion Matrix:
# [[262  42  10]
#  [ 10  61   4]
#  [  2  12  23]]

# ============================================================

# Model: Neural Network
# Accuracy: 0.8286
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.83      1.00      0.90       314
#          2.0       0.88      0.09      0.17        75
#          3.0       0.84      0.86      0.85        37

#     accuracy                           0.83       426
#    macro avg       0.85      0.65      0.64       426
# weighted avg       0.84      0.83      0.77       426

# Confusion Matrix:
# [[314   0   0]
#  [ 62   7   6]
#  [  4   1  32]]

# ============================================================

# Model: AdaBoost
# Accuracy: 0.8779
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.90      0.95      0.92       314
#          2.0       0.76      0.71      0.73        75
#          3.0       0.89      0.65      0.75        37

#     accuracy                           0.88       426
#    macro avg       0.85      0.77      0.80       426
# weighted avg       0.88      0.88      0.87       426

# Confusion Matrix:
# [[297  16   1]
#  [ 20  53   2]
#  [ 12   1  24]]

# ============================================================

# Model: Extra Trees
# Accuracy: 0.9366
# Classification Report:
#               precision    recall  f1-score   support

#          1.0       0.95      0.99      0.97       314
#          2.0       0.92      0.72      0.81        75
#          3.0       0.89      0.92      0.91        37

#     accuracy                           0.94       426
#    macro avg       0.92      0.88      0.89       426
# weighted avg       0.94      0.94      0.93       426

# Confusion Matrix:
# [[311   3   0]
#  [ 17  54   4]
#  [  1   2  34]]

# ============================================================

